/*
 * CDS - GtmEntries
 *
 * CDS - GtmEntries
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIMDemo.Models
{ 
    /// <summary>
    /// Record
    /// </summary>
    [DataContract]
    public partial class Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord : IEquatable<Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord>
    { 
        /// <summary>
        /// @odata.type
        /// </summary>
        /// <value>@odata.type</value>
        [Required]
        [DataMember(Name="@odata.type")]
        public string OdataType { get; set; }

        /// <summary>
        /// cat_gtmentryid
        /// </summary>
        /// <value>cat_gtmentryid</value>
        [Required]
        [DataMember(Name="cat_gtmentryid")]
        public string CatGtmentryid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord {\n");
            sb.Append("  OdataType: ").Append(OdataType).Append("\n");
            sb.Append("  CatGtmentryid: ").Append(CatGtmentryid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord)obj);
        }

        /// <summary>
        /// Returns true if Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord instances are equal
        /// </summary>
        /// <param name="other">Instance of Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OdataType == other.OdataType ||
                    OdataType != null &&
                    OdataType.Equals(other.OdataType)
                ) && 
                (
                    CatGtmentryid == other.CatGtmentryid ||
                    CatGtmentryid != null &&
                    CatGtmentryid.Equals(other.CatGtmentryid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (OdataType != null)
                    hashCode = hashCode * 59 + OdataType.GetHashCode();
                    if (CatGtmentryid != null)
                    hashCode = hashCode * 59 + CatGtmentryid.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord left, Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord left, Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
