/*
 * CDS - GtmEntries
 *
 * CDS - GtmEntries
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIMDemo.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Body2 : IEquatable<Body2>
    { 
        /// <summary>
        /// Gets or Sets Record
        /// </summary>
        [Required]
        [DataMember(Name="Record")]
        public Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamRecord Record { get; set; }

        /// <summary>
        /// Gets or Sets TeamTemplate
        /// </summary>
        [Required]
        [DataMember(Name="TeamTemplate")]
        public Apidatav90systemusersuserIDMicrosoftDynamicsCRMRemoveUserFromRecordTeamTeamTemplate TeamTemplate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Body2 {\n");
            sb.Append("  Record: ").Append(Record).Append("\n");
            sb.Append("  TeamTemplate: ").Append(TeamTemplate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Body2)obj);
        }

        /// <summary>
        /// Returns true if Body2 instances are equal
        /// </summary>
        /// <param name="other">Instance of Body2 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Body2 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Record == other.Record ||
                    Record != null &&
                    Record.Equals(other.Record)
                ) && 
                (
                    TeamTemplate == other.TeamTemplate ||
                    TeamTemplate != null &&
                    TeamTemplate.Equals(other.TeamTemplate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Record != null)
                    hashCode = hashCode * 59 + Record.GetHashCode();
                    if (TeamTemplate != null)
                    hashCode = hashCode * 59 + TeamTemplate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Body2 left, Body2 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Body2 left, Body2 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
