/*
 * CDS - GtmEntries
 *
 * CDS - GtmEntries
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIMDemo.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponseDefault6OptionSetDescriptionLocalizedLabels : IEquatable<InlineResponseDefault6OptionSetDescriptionLocalizedLabels>
    { 
        /// <summary>
        /// Label
        /// </summary>
        /// <value>Label</value>
        [DataMember(Name="Label")]
        public string Label { get; set; }

        /// <summary>
        /// LanguageCode
        /// </summary>
        /// <value>LanguageCode</value>
        [DataMember(Name="LanguageCode")]
        public int? LanguageCode { get; set; }

        /// <summary>
        /// IsManaged
        /// </summary>
        /// <value>IsManaged</value>
        [DataMember(Name="IsManaged")]
        public bool? IsManaged { get; set; }

        /// <summary>
        /// MetadataId
        /// </summary>
        /// <value>MetadataId</value>
        [DataMember(Name="MetadataId")]
        public string MetadataId { get; set; }

        /// <summary>
        /// HasChanged
        /// </summary>
        /// <value>HasChanged</value>
        [DataMember(Name="HasChanged")]
        public string HasChanged { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault6OptionSetDescriptionLocalizedLabels {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  LanguageCode: ").Append(LanguageCode).Append("\n");
            sb.Append("  IsManaged: ").Append(IsManaged).Append("\n");
            sb.Append("  MetadataId: ").Append(MetadataId).Append("\n");
            sb.Append("  HasChanged: ").Append(HasChanged).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponseDefault6OptionSetDescriptionLocalizedLabels)obj);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault6OptionSetDescriptionLocalizedLabels instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponseDefault6OptionSetDescriptionLocalizedLabels to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault6OptionSetDescriptionLocalizedLabels other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Label == other.Label ||
                    Label != null &&
                    Label.Equals(other.Label)
                ) && 
                (
                    LanguageCode == other.LanguageCode ||
                    LanguageCode != null &&
                    LanguageCode.Equals(other.LanguageCode)
                ) && 
                (
                    IsManaged == other.IsManaged ||
                    IsManaged != null &&
                    IsManaged.Equals(other.IsManaged)
                ) && 
                (
                    MetadataId == other.MetadataId ||
                    MetadataId != null &&
                    MetadataId.Equals(other.MetadataId)
                ) && 
                (
                    HasChanged == other.HasChanged ||
                    HasChanged != null &&
                    HasChanged.Equals(other.HasChanged)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Label != null)
                    hashCode = hashCode * 59 + Label.GetHashCode();
                    if (LanguageCode != null)
                    hashCode = hashCode * 59 + LanguageCode.GetHashCode();
                    if (IsManaged != null)
                    hashCode = hashCode * 59 + IsManaged.GetHashCode();
                    if (MetadataId != null)
                    hashCode = hashCode * 59 + MetadataId.GetHashCode();
                    if (HasChanged != null)
                    hashCode = hashCode * 59 + HasChanged.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponseDefault6OptionSetDescriptionLocalizedLabels left, InlineResponseDefault6OptionSetDescriptionLocalizedLabels right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponseDefault6OptionSetDescriptionLocalizedLabels left, InlineResponseDefault6OptionSetDescriptionLocalizedLabels right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
