/*
 * CDS - GtmEntries
 *
 * CDS - GtmEntries
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIMDemo.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponseDefault3 : IEquatable<InlineResponseDefault3>
    { 
        /// <summary>
        /// @odata.context
        /// </summary>
        /// <value>@odata.context</value>
        [DataMember(Name="@odata.context")]
        public string OdataContext { get; set; }

        /// <summary>
        /// @odata.etag
        /// </summary>
        /// <value>@odata.etag</value>
        [DataMember(Name="@odata.etag")]
        public string OdataEtag { get; set; }

        /// <summary>
        /// systemuserid
        /// </summary>
        /// <value>systemuserid</value>
        [DataMember(Name="systemuserid")]
        public string Systemuserid { get; set; }

        /// <summary>
        /// accessmode
        /// </summary>
        /// <value>accessmode</value>
        [DataMember(Name="accessmode")]
        public int? Accessmode { get; set; }

        /// <summary>
        /// firstname
        /// </summary>
        /// <value>firstname</value>
        [DataMember(Name="firstname")]
        public string Firstname { get; set; }

        /// <summary>
        /// setupuser
        /// </summary>
        /// <value>setupuser</value>
        [DataMember(Name="setupuser")]
        public bool? Setupuser { get; set; }

        /// <summary>
        /// address1_addressid
        /// </summary>
        /// <value>address1_addressid</value>
        [DataMember(Name="address1_addressid")]
        public string Address1Addressid { get; set; }

        /// <summary>
        /// incomingemaildeliverymethod
        /// </summary>
        /// <value>incomingemaildeliverymethod</value>
        [DataMember(Name="incomingemaildeliverymethod")]
        public int? Incomingemaildeliverymethod { get; set; }

        /// <summary>
        /// internalemailaddress
        /// </summary>
        /// <value>internalemailaddress</value>
        [DataMember(Name="internalemailaddress")]
        public string Internalemailaddress { get; set; }

        /// <summary>
        /// identityid
        /// </summary>
        /// <value>identityid</value>
        [DataMember(Name="identityid")]
        public int? Identityid { get; set; }

        /// <summary>
        /// domainname
        /// </summary>
        /// <value>domainname</value>
        [DataMember(Name="domainname")]
        public string Domainname { get; set; }

        /// <summary>
        /// _queueid_value
        /// </summary>
        /// <value>_queueid_value</value>
        [DataMember(Name="_queueid_value")]
        public string QueueidValue { get; set; }

        /// <summary>
        /// entityimageid
        /// </summary>
        /// <value>entityimageid</value>
        [DataMember(Name="entityimageid")]
        public string Entityimageid { get; set; }

        /// <summary>
        /// isintegrationuser
        /// </summary>
        /// <value>isintegrationuser</value>
        [DataMember(Name="isintegrationuser")]
        public bool? Isintegrationuser { get; set; }

        /// <summary>
        /// createdon
        /// </summary>
        /// <value>createdon</value>
        [DataMember(Name="createdon")]
        public string Createdon { get; set; }

        /// <summary>
        /// entityimage_timestamp
        /// </summary>
        /// <value>entityimage_timestamp</value>
        [DataMember(Name="entityimage_timestamp")]
        public int? EntityimageTimestamp { get; set; }

        /// <summary>
        /// _calendarid_value
        /// </summary>
        /// <value>_calendarid_value</value>
        [DataMember(Name="_calendarid_value")]
        public string CalendaridValue { get; set; }

        /// <summary>
        /// windowsliveid
        /// </summary>
        /// <value>windowsliveid</value>
        [DataMember(Name="windowsliveid")]
        public string Windowsliveid { get; set; }

        /// <summary>
        /// _businessunitid_value
        /// </summary>
        /// <value>_businessunitid_value</value>
        [DataMember(Name="_businessunitid_value")]
        public string BusinessunitidValue { get; set; }

        /// <summary>
        /// caltype
        /// </summary>
        /// <value>caltype</value>
        [DataMember(Name="caltype")]
        public int? Caltype { get; set; }

        /// <summary>
        /// modifiedon
        /// </summary>
        /// <value>modifiedon</value>
        [DataMember(Name="modifiedon")]
        public string Modifiedon { get; set; }

        /// <summary>
        /// defaultfilterspopulated
        /// </summary>
        /// <value>defaultfilterspopulated</value>
        [DataMember(Name="defaultfilterspopulated")]
        public bool? Defaultfilterspopulated { get; set; }

        /// <summary>
        /// outgoingemaildeliverymethod
        /// </summary>
        /// <value>outgoingemaildeliverymethod</value>
        [DataMember(Name="outgoingemaildeliverymethod")]
        public int? Outgoingemaildeliverymethod { get; set; }

        /// <summary>
        /// title
        /// </summary>
        /// <value>title</value>
        [DataMember(Name="title")]
        public string Title { get; set; }

        /// <summary>
        /// emailrouteraccessapproval
        /// </summary>
        /// <value>emailrouteraccessapproval</value>
        [DataMember(Name="emailrouteraccessapproval")]
        public int? Emailrouteraccessapproval { get; set; }

        /// <summary>
        /// lastname
        /// </summary>
        /// <value>lastname</value>
        [DataMember(Name="lastname")]
        public string Lastname { get; set; }

        /// <summary>
        /// fullname
        /// </summary>
        /// <value>fullname</value>
        [DataMember(Name="fullname")]
        public string Fullname { get; set; }

        /// <summary>
        /// issyncwithdirectory
        /// </summary>
        /// <value>issyncwithdirectory</value>
        [DataMember(Name="issyncwithdirectory")]
        public bool? Issyncwithdirectory { get; set; }

        /// <summary>
        /// userlicensetype
        /// </summary>
        /// <value>userlicensetype</value>
        [DataMember(Name="userlicensetype")]
        public int? Userlicensetype { get; set; }

        /// <summary>
        /// azureactivedirectoryobjectid
        /// </summary>
        /// <value>azureactivedirectoryobjectid</value>
        [DataMember(Name="azureactivedirectoryobjectid")]
        public string Azureactivedirectoryobjectid { get; set; }

        /// <summary>
        /// _modifiedby_value
        /// </summary>
        /// <value>_modifiedby_value</value>
        [DataMember(Name="_modifiedby_value")]
        public string ModifiedbyValue { get; set; }

        /// <summary>
        /// organizationid
        /// </summary>
        /// <value>organizationid</value>
        [DataMember(Name="organizationid")]
        public string Organizationid { get; set; }

        /// <summary>
        /// defaultodbfoldername
        /// </summary>
        /// <value>defaultodbfoldername</value>
        [DataMember(Name="defaultodbfoldername")]
        public string Defaultodbfoldername { get; set; }

        /// <summary>
        /// versionnumber
        /// </summary>
        /// <value>versionnumber</value>
        [DataMember(Name="versionnumber")]
        public int? Versionnumber { get; set; }

        /// <summary>
        /// isemailaddressapprovedbyo365admin
        /// </summary>
        /// <value>isemailaddressapprovedbyo365admin</value>
        [DataMember(Name="isemailaddressapprovedbyo365admin")]
        public bool? Isemailaddressapprovedbyo365admin { get; set; }

        /// <summary>
        /// invitestatuscode
        /// </summary>
        /// <value>invitestatuscode</value>
        [DataMember(Name="invitestatuscode")]
        public int? Invitestatuscode { get; set; }

        /// <summary>
        /// yomifullname
        /// </summary>
        /// <value>yomifullname</value>
        [DataMember(Name="yomifullname")]
        public string Yomifullname { get; set; }

        /// <summary>
        /// entityimage_url
        /// </summary>
        /// <value>entityimage_url</value>
        [DataMember(Name="entityimage_url")]
        public string EntityimageUrl { get; set; }

        /// <summary>
        /// isdisabled
        /// </summary>
        /// <value>isdisabled</value>
        [DataMember(Name="isdisabled")]
        public bool? Isdisabled { get; set; }

        /// <summary>
        /// userpuid
        /// </summary>
        /// <value>userpuid</value>
        [DataMember(Name="userpuid")]
        public string Userpuid { get; set; }

        /// <summary>
        /// address2_addressid
        /// </summary>
        /// <value>address2_addressid</value>
        [DataMember(Name="address2_addressid")]
        public string Address2Addressid { get; set; }

        /// <summary>
        /// _defaultmailbox_value
        /// </summary>
        /// <value>_defaultmailbox_value</value>
        [DataMember(Name="_defaultmailbox_value")]
        public string DefaultmailboxValue { get; set; }

        /// <summary>
        /// entityimage
        /// </summary>
        /// <value>entityimage</value>
        [DataMember(Name="entityimage")]
        public string Entityimage { get; set; }

        /// <summary>
        /// islicensed
        /// </summary>
        /// <value>islicensed</value>
        [DataMember(Name="islicensed")]
        public bool? Islicensed { get; set; }

        /// <summary>
        /// ownerid
        /// </summary>
        /// <value>ownerid</value>
        [DataMember(Name="ownerid")]
        public string Ownerid { get; set; }

        /// <summary>
        /// address1_fax
        /// </summary>
        /// <value>address1_fax</value>
        [DataMember(Name="address1_fax")]
        public string Address1Fax { get; set; }

        /// <summary>
        /// address1_postofficebox
        /// </summary>
        /// <value>address1_postofficebox</value>
        [DataMember(Name="address1_postofficebox")]
        public string Address1Postofficebox { get; set; }

        /// <summary>
        /// address1_upszone
        /// </summary>
        /// <value>address1_upszone</value>
        [DataMember(Name="address1_upszone")]
        public string Address1Upszone { get; set; }

        /// <summary>
        /// photourl
        /// </summary>
        /// <value>photourl</value>
        [DataMember(Name="photourl")]
        public string Photourl { get; set; }

        /// <summary>
        /// address1_latitude
        /// </summary>
        /// <value>address1_latitude</value>
        [DataMember(Name="address1_latitude")]
        public string Address1Latitude { get; set; }

        /// <summary>
        /// address1_shippingmethodcode
        /// </summary>
        /// <value>address1_shippingmethodcode</value>
        [DataMember(Name="address1_shippingmethodcode")]
        public string Address1Shippingmethodcode { get; set; }

        /// <summary>
        /// address1_utcoffset
        /// </summary>
        /// <value>address1_utcoffset</value>
        [DataMember(Name="address1_utcoffset")]
        public string Address1Utcoffset { get; set; }

        /// <summary>
        /// _createdonbehalfby_value
        /// </summary>
        /// <value>_createdonbehalfby_value</value>
        [DataMember(Name="_createdonbehalfby_value")]
        public string CreatedonbehalfbyValue { get; set; }

        /// <summary>
        /// homephone
        /// </summary>
        /// <value>homephone</value>
        [DataMember(Name="homephone")]
        public string Homephone { get; set; }

        /// <summary>
        /// skills
        /// </summary>
        /// <value>skills</value>
        [DataMember(Name="skills")]
        public string Skills { get; set; }

        /// <summary>
        /// address2_latitude
        /// </summary>
        /// <value>address2_latitude</value>
        [DataMember(Name="address2_latitude")]
        public string Address2Latitude { get; set; }

        /// <summary>
        /// _cat_fullname_value
        /// </summary>
        /// <value>_cat_fullname_value</value>
        [DataMember(Name="_cat_fullname_value")]
        public string CatFullnameValue { get; set; }

        /// <summary>
        /// _createdby_value
        /// </summary>
        /// <value>_createdby_value</value>
        [DataMember(Name="_createdby_value")]
        public string CreatedbyValue { get; set; }

        /// <summary>
        /// governmentid
        /// </summary>
        /// <value>governmentid</value>
        [DataMember(Name="governmentid")]
        public string Governmentid { get; set; }

        /// <summary>
        /// _parentsystemuserid_value
        /// </summary>
        /// <value>_parentsystemuserid_value</value>
        [DataMember(Name="_parentsystemuserid_value")]
        public string ParentsystemuseridValue { get; set; }

        /// <summary>
        /// address2_stateorprovince
        /// </summary>
        /// <value>address2_stateorprovince</value>
        [DataMember(Name="address2_stateorprovince")]
        public string Address2Stateorprovince { get; set; }

        /// <summary>
        /// address2_longitude
        /// </summary>
        /// <value>address2_longitude</value>
        [DataMember(Name="address2_longitude")]
        public string Address2Longitude { get; set; }

        /// <summary>
        /// address2_city
        /// </summary>
        /// <value>address2_city</value>
        [DataMember(Name="address2_city")]
        public string Address2City { get; set; }

        /// <summary>
        /// address1_telephone3
        /// </summary>
        /// <value>address1_telephone3</value>
        [DataMember(Name="address1_telephone3")]
        public string Address1Telephone3 { get; set; }

        /// <summary>
        /// mobilephone
        /// </summary>
        /// <value>mobilephone</value>
        [DataMember(Name="mobilephone")]
        public string Mobilephone { get; set; }

        /// <summary>
        /// address2_fax
        /// </summary>
        /// <value>address2_fax</value>
        [DataMember(Name="address2_fax")]
        public string Address2Fax { get; set; }

        /// <summary>
        /// preferredaddresscode
        /// </summary>
        /// <value>preferredaddresscode</value>
        [DataMember(Name="preferredaddresscode")]
        public string Preferredaddresscode { get; set; }

        /// <summary>
        /// address1_name
        /// </summary>
        /// <value>address1_name</value>
        [DataMember(Name="address1_name")]
        public string Address1Name { get; set; }

        /// <summary>
        /// address2_line2
        /// </summary>
        /// <value>address2_line2</value>
        [DataMember(Name="address2_line2")]
        public string Address2Line2 { get; set; }

        /// <summary>
        /// passporthi
        /// </summary>
        /// <value>passporthi</value>
        [DataMember(Name="passporthi")]
        public string Passporthi { get; set; }

        /// <summary>
        /// _territoryid_value
        /// </summary>
        /// <value>_territoryid_value</value>
        [DataMember(Name="_territoryid_value")]
        public string TerritoryidValue { get; set; }

        /// <summary>
        /// _modifiedonbehalfby_value
        /// </summary>
        /// <value>_modifiedonbehalfby_value</value>
        [DataMember(Name="_modifiedonbehalfby_value")]
        public string ModifiedonbehalfbyValue { get; set; }

        /// <summary>
        /// address1_stateorprovince
        /// </summary>
        /// <value>address1_stateorprovince</value>
        [DataMember(Name="address1_stateorprovince")]
        public string Address1Stateorprovince { get; set; }

        /// <summary>
        /// applicationid
        /// </summary>
        /// <value>applicationid</value>
        [DataMember(Name="applicationid")]
        public string Applicationid { get; set; }

        /// <summary>
        /// salutation
        /// </summary>
        /// <value>salutation</value>
        [DataMember(Name="salutation")]
        public string Salutation { get; set; }

        /// <summary>
        /// address1_county
        /// </summary>
        /// <value>address1_county</value>
        [DataMember(Name="address1_county")]
        public string Address1County { get; set; }

        /// <summary>
        /// address2_line3
        /// </summary>
        /// <value>address2_line3</value>
        [DataMember(Name="address2_line3")]
        public string Address2Line3 { get; set; }

        /// <summary>
        /// stageid
        /// </summary>
        /// <value>stageid</value>
        [DataMember(Name="stageid")]
        public string Stageid { get; set; }

        /// <summary>
        /// address1_longitude
        /// </summary>
        /// <value>address1_longitude</value>
        [DataMember(Name="address1_longitude")]
        public string Address1Longitude { get; set; }

        /// <summary>
        /// address1_addresstypecode
        /// </summary>
        /// <value>address1_addresstypecode</value>
        [DataMember(Name="address1_addresstypecode")]
        public string Address1Addresstypecode { get; set; }

        /// <summary>
        /// address2_postalcode
        /// </summary>
        /// <value>address2_postalcode</value>
        [DataMember(Name="address2_postalcode")]
        public string Address2Postalcode { get; set; }

        /// <summary>
        /// passportlo
        /// </summary>
        /// <value>passportlo</value>
        [DataMember(Name="passportlo")]
        public string Passportlo { get; set; }

        /// <summary>
        /// importsequencenumber
        /// </summary>
        /// <value>importsequencenumber</value>
        [DataMember(Name="importsequencenumber")]
        public string Importsequencenumber { get; set; }

        /// <summary>
        /// timezoneruleversionnumber
        /// </summary>
        /// <value>timezoneruleversionnumber</value>
        [DataMember(Name="timezoneruleversionnumber")]
        public string Timezoneruleversionnumber { get; set; }

        /// <summary>
        /// sharepointemailaddress
        /// </summary>
        /// <value>sharepointemailaddress</value>
        [DataMember(Name="sharepointemailaddress")]
        public string Sharepointemailaddress { get; set; }

        /// <summary>
        /// yammeruserid
        /// </summary>
        /// <value>yammeruserid</value>
        [DataMember(Name="yammeruserid")]
        public string Yammeruserid { get; set; }

        /// <summary>
        /// nickname
        /// </summary>
        /// <value>nickname</value>
        [DataMember(Name="nickname")]
        public string Nickname { get; set; }

        /// <summary>
        /// address1_composite
        /// </summary>
        /// <value>address1_composite</value>
        [DataMember(Name="address1_composite")]
        public string Address1Composite { get; set; }

        /// <summary>
        /// overriddencreatedon
        /// </summary>
        /// <value>overriddencreatedon</value>
        [DataMember(Name="overriddencreatedon")]
        public string Overriddencreatedon { get; set; }

        /// <summary>
        /// personalemailaddress
        /// </summary>
        /// <value>personalemailaddress</value>
        [DataMember(Name="personalemailaddress")]
        public string Personalemailaddress { get; set; }

        /// <summary>
        /// utcconversiontimezonecode
        /// </summary>
        /// <value>utcconversiontimezonecode</value>
        [DataMember(Name="utcconversiontimezonecode")]
        public string Utcconversiontimezonecode { get; set; }

        /// <summary>
        /// preferredemailcode
        /// </summary>
        /// <value>preferredemailcode</value>
        [DataMember(Name="preferredemailcode")]
        public string Preferredemailcode { get; set; }

        /// <summary>
        /// address2_composite
        /// </summary>
        /// <value>address2_composite</value>
        [DataMember(Name="address2_composite")]
        public string Address2Composite { get; set; }

        /// <summary>
        /// address1_telephone1
        /// </summary>
        /// <value>address1_telephone1</value>
        [DataMember(Name="address1_telephone1")]
        public string Address1Telephone1 { get; set; }

        /// <summary>
        /// _mobileofflineprofileid_value
        /// </summary>
        /// <value>_mobileofflineprofileid_value</value>
        [DataMember(Name="_mobileofflineprofileid_value")]
        public string MobileofflineprofileidValue { get; set; }

        /// <summary>
        /// address2_country
        /// </summary>
        /// <value>address2_country</value>
        [DataMember(Name="address2_country")]
        public string Address2Country { get; set; }

        /// <summary>
        /// address1_line1
        /// </summary>
        /// <value>address1_line1</value>
        [DataMember(Name="address1_line1")]
        public string Address1Line1 { get; set; }

        /// <summary>
        /// yomimiddlename
        /// </summary>
        /// <value>yomimiddlename</value>
        [DataMember(Name="yomimiddlename")]
        public string Yomimiddlename { get; set; }

        /// <summary>
        /// _transactioncurrencyid_value
        /// </summary>
        /// <value>_transactioncurrencyid_value</value>
        [DataMember(Name="_transactioncurrencyid_value")]
        public string TransactioncurrencyidValue { get; set; }

        /// <summary>
        /// address1_line3
        /// </summary>
        /// <value>address1_line3</value>
        [DataMember(Name="address1_line3")]
        public string Address1Line3 { get; set; }

        /// <summary>
        /// address1_line2
        /// </summary>
        /// <value>address1_line2</value>
        [DataMember(Name="address1_line2")]
        public string Address1Line2 { get; set; }

        /// <summary>
        /// address1_city
        /// </summary>
        /// <value>address1_city</value>
        [DataMember(Name="address1_city")]
        public string Address1City { get; set; }

        /// <summary>
        /// disabledreason
        /// </summary>
        /// <value>disabledreason</value>
        [DataMember(Name="disabledreason")]
        public string Disabledreason { get; set; }

        /// <summary>
        /// address2_name
        /// </summary>
        /// <value>address2_name</value>
        [DataMember(Name="address2_name")]
        public string Address2Name { get; set; }

        /// <summary>
        /// _positionid_value
        /// </summary>
        /// <value>_positionid_value</value>
        [DataMember(Name="_positionid_value")]
        public string PositionidValue { get; set; }

        /// <summary>
        /// address2_line1
        /// </summary>
        /// <value>address2_line1</value>
        [DataMember(Name="address2_line1")]
        public string Address2Line1 { get; set; }

        /// <summary>
        /// middlename
        /// </summary>
        /// <value>middlename</value>
        [DataMember(Name="middlename")]
        public string Middlename { get; set; }

        /// <summary>
        /// preferredphonecode
        /// </summary>
        /// <value>preferredphonecode</value>
        [DataMember(Name="preferredphonecode")]
        public string Preferredphonecode { get; set; }

        /// <summary>
        /// employeeid
        /// </summary>
        /// <value>employeeid</value>
        [DataMember(Name="employeeid")]
        public string Employeeid { get; set; }

        /// <summary>
        /// mobilealertemail
        /// </summary>
        /// <value>mobilealertemail</value>
        [DataMember(Name="mobilealertemail")]
        public string Mobilealertemail { get; set; }

        /// <summary>
        /// address2_telephone2
        /// </summary>
        /// <value>address2_telephone2</value>
        [DataMember(Name="address2_telephone2")]
        public string Address2Telephone2 { get; set; }

        /// <summary>
        /// address2_telephone1
        /// </summary>
        /// <value>address2_telephone1</value>
        [DataMember(Name="address2_telephone1")]
        public string Address2Telephone1 { get; set; }

        /// <summary>
        /// traversedpath
        /// </summary>
        /// <value>traversedpath</value>
        [DataMember(Name="traversedpath")]
        public string Traversedpath { get; set; }

        /// <summary>
        /// address2_county
        /// </summary>
        /// <value>address2_county</value>
        [DataMember(Name="address2_county")]
        public string Address2County { get; set; }

        /// <summary>
        /// yomifirstname
        /// </summary>
        /// <value>yomifirstname</value>
        [DataMember(Name="yomifirstname")]
        public string Yomifirstname { get; set; }

        /// <summary>
        /// address2_shippingmethodcode
        /// </summary>
        /// <value>address2_shippingmethodcode</value>
        [DataMember(Name="address2_shippingmethodcode")]
        public string Address2Shippingmethodcode { get; set; }

        /// <summary>
        /// address2_telephone3
        /// </summary>
        /// <value>address2_telephone3</value>
        [DataMember(Name="address2_telephone3")]
        public string Address2Telephone3 { get; set; }

        /// <summary>
        /// yomilastname
        /// </summary>
        /// <value>yomilastname</value>
        [DataMember(Name="yomilastname")]
        public string Yomilastname { get; set; }

        /// <summary>
        /// displayinserviceviews
        /// </summary>
        /// <value>displayinserviceviews</value>
        [DataMember(Name="displayinserviceviews")]
        public string Displayinserviceviews { get; set; }

        /// <summary>
        /// address2_addresstypecode
        /// </summary>
        /// <value>address2_addresstypecode</value>
        [DataMember(Name="address2_addresstypecode")]
        public string Address2Addresstypecode { get; set; }

        /// <summary>
        /// yammeremailaddress
        /// </summary>
        /// <value>yammeremailaddress</value>
        [DataMember(Name="yammeremailaddress")]
        public string Yammeremailaddress { get; set; }

        /// <summary>
        /// address1_postalcode
        /// </summary>
        /// <value>address1_postalcode</value>
        [DataMember(Name="address1_postalcode")]
        public string Address1Postalcode { get; set; }

        /// <summary>
        /// exchangerate
        /// </summary>
        /// <value>exchangerate</value>
        [DataMember(Name="exchangerate")]
        public string Exchangerate { get; set; }

        /// <summary>
        /// jobtitle
        /// </summary>
        /// <value>jobtitle</value>
        [DataMember(Name="jobtitle")]
        public string Jobtitle { get; set; }

        /// <summary>
        /// address2_postofficebox
        /// </summary>
        /// <value>address2_postofficebox</value>
        [DataMember(Name="address2_postofficebox")]
        public string Address2Postofficebox { get; set; }

        /// <summary>
        /// address2_upszone
        /// </summary>
        /// <value>address2_upszone</value>
        [DataMember(Name="address2_upszone")]
        public string Address2Upszone { get; set; }

        /// <summary>
        /// processid
        /// </summary>
        /// <value>processid</value>
        [DataMember(Name="processid")]
        public string Processid { get; set; }

        /// <summary>
        /// applicationiduri
        /// </summary>
        /// <value>applicationiduri</value>
        [DataMember(Name="applicationiduri")]
        public string Applicationiduri { get; set; }

        /// <summary>
        /// address2_utcoffset
        /// </summary>
        /// <value>address2_utcoffset</value>
        [DataMember(Name="address2_utcoffset")]
        public string Address2Utcoffset { get; set; }

        /// <summary>
        /// address1_telephone2
        /// </summary>
        /// <value>address1_telephone2</value>
        [DataMember(Name="address1_telephone2")]
        public string Address1Telephone2 { get; set; }

        /// <summary>
        /// address1_country
        /// </summary>
        /// <value>address1_country</value>
        [DataMember(Name="address1_country")]
        public string Address1Country { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault3 {\n");
            sb.Append("  OdataContext: ").Append(OdataContext).Append("\n");
            sb.Append("  OdataEtag: ").Append(OdataEtag).Append("\n");
            sb.Append("  Systemuserid: ").Append(Systemuserid).Append("\n");
            sb.Append("  Accessmode: ").Append(Accessmode).Append("\n");
            sb.Append("  Firstname: ").Append(Firstname).Append("\n");
            sb.Append("  Setupuser: ").Append(Setupuser).Append("\n");
            sb.Append("  Address1Addressid: ").Append(Address1Addressid).Append("\n");
            sb.Append("  Incomingemaildeliverymethod: ").Append(Incomingemaildeliverymethod).Append("\n");
            sb.Append("  Internalemailaddress: ").Append(Internalemailaddress).Append("\n");
            sb.Append("  Identityid: ").Append(Identityid).Append("\n");
            sb.Append("  Domainname: ").Append(Domainname).Append("\n");
            sb.Append("  QueueidValue: ").Append(QueueidValue).Append("\n");
            sb.Append("  Entityimageid: ").Append(Entityimageid).Append("\n");
            sb.Append("  Isintegrationuser: ").Append(Isintegrationuser).Append("\n");
            sb.Append("  Createdon: ").Append(Createdon).Append("\n");
            sb.Append("  EntityimageTimestamp: ").Append(EntityimageTimestamp).Append("\n");
            sb.Append("  CalendaridValue: ").Append(CalendaridValue).Append("\n");
            sb.Append("  Windowsliveid: ").Append(Windowsliveid).Append("\n");
            sb.Append("  BusinessunitidValue: ").Append(BusinessunitidValue).Append("\n");
            sb.Append("  Caltype: ").Append(Caltype).Append("\n");
            sb.Append("  Modifiedon: ").Append(Modifiedon).Append("\n");
            sb.Append("  Defaultfilterspopulated: ").Append(Defaultfilterspopulated).Append("\n");
            sb.Append("  Outgoingemaildeliverymethod: ").Append(Outgoingemaildeliverymethod).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Emailrouteraccessapproval: ").Append(Emailrouteraccessapproval).Append("\n");
            sb.Append("  Lastname: ").Append(Lastname).Append("\n");
            sb.Append("  Fullname: ").Append(Fullname).Append("\n");
            sb.Append("  Issyncwithdirectory: ").Append(Issyncwithdirectory).Append("\n");
            sb.Append("  Userlicensetype: ").Append(Userlicensetype).Append("\n");
            sb.Append("  Azureactivedirectoryobjectid: ").Append(Azureactivedirectoryobjectid).Append("\n");
            sb.Append("  ModifiedbyValue: ").Append(ModifiedbyValue).Append("\n");
            sb.Append("  Organizationid: ").Append(Organizationid).Append("\n");
            sb.Append("  Defaultodbfoldername: ").Append(Defaultodbfoldername).Append("\n");
            sb.Append("  Versionnumber: ").Append(Versionnumber).Append("\n");
            sb.Append("  Isemailaddressapprovedbyo365admin: ").Append(Isemailaddressapprovedbyo365admin).Append("\n");
            sb.Append("  Invitestatuscode: ").Append(Invitestatuscode).Append("\n");
            sb.Append("  Yomifullname: ").Append(Yomifullname).Append("\n");
            sb.Append("  EntityimageUrl: ").Append(EntityimageUrl).Append("\n");
            sb.Append("  Isdisabled: ").Append(Isdisabled).Append("\n");
            sb.Append("  Userpuid: ").Append(Userpuid).Append("\n");
            sb.Append("  Address2Addressid: ").Append(Address2Addressid).Append("\n");
            sb.Append("  DefaultmailboxValue: ").Append(DefaultmailboxValue).Append("\n");
            sb.Append("  Entityimage: ").Append(Entityimage).Append("\n");
            sb.Append("  Islicensed: ").Append(Islicensed).Append("\n");
            sb.Append("  Ownerid: ").Append(Ownerid).Append("\n");
            sb.Append("  Address1Fax: ").Append(Address1Fax).Append("\n");
            sb.Append("  Address1Postofficebox: ").Append(Address1Postofficebox).Append("\n");
            sb.Append("  Address1Upszone: ").Append(Address1Upszone).Append("\n");
            sb.Append("  Photourl: ").Append(Photourl).Append("\n");
            sb.Append("  Address1Latitude: ").Append(Address1Latitude).Append("\n");
            sb.Append("  Address1Shippingmethodcode: ").Append(Address1Shippingmethodcode).Append("\n");
            sb.Append("  Address1Utcoffset: ").Append(Address1Utcoffset).Append("\n");
            sb.Append("  CreatedonbehalfbyValue: ").Append(CreatedonbehalfbyValue).Append("\n");
            sb.Append("  Homephone: ").Append(Homephone).Append("\n");
            sb.Append("  Skills: ").Append(Skills).Append("\n");
            sb.Append("  Address2Latitude: ").Append(Address2Latitude).Append("\n");
            sb.Append("  CatFullnameValue: ").Append(CatFullnameValue).Append("\n");
            sb.Append("  CreatedbyValue: ").Append(CreatedbyValue).Append("\n");
            sb.Append("  Governmentid: ").Append(Governmentid).Append("\n");
            sb.Append("  ParentsystemuseridValue: ").Append(ParentsystemuseridValue).Append("\n");
            sb.Append("  Address2Stateorprovince: ").Append(Address2Stateorprovince).Append("\n");
            sb.Append("  Address2Longitude: ").Append(Address2Longitude).Append("\n");
            sb.Append("  Address2City: ").Append(Address2City).Append("\n");
            sb.Append("  Address1Telephone3: ").Append(Address1Telephone3).Append("\n");
            sb.Append("  Mobilephone: ").Append(Mobilephone).Append("\n");
            sb.Append("  Address2Fax: ").Append(Address2Fax).Append("\n");
            sb.Append("  Preferredaddresscode: ").Append(Preferredaddresscode).Append("\n");
            sb.Append("  Address1Name: ").Append(Address1Name).Append("\n");
            sb.Append("  Address2Line2: ").Append(Address2Line2).Append("\n");
            sb.Append("  Passporthi: ").Append(Passporthi).Append("\n");
            sb.Append("  TerritoryidValue: ").Append(TerritoryidValue).Append("\n");
            sb.Append("  ModifiedonbehalfbyValue: ").Append(ModifiedonbehalfbyValue).Append("\n");
            sb.Append("  Address1Stateorprovince: ").Append(Address1Stateorprovince).Append("\n");
            sb.Append("  Applicationid: ").Append(Applicationid).Append("\n");
            sb.Append("  Salutation: ").Append(Salutation).Append("\n");
            sb.Append("  Address1County: ").Append(Address1County).Append("\n");
            sb.Append("  Address2Line3: ").Append(Address2Line3).Append("\n");
            sb.Append("  Stageid: ").Append(Stageid).Append("\n");
            sb.Append("  Address1Longitude: ").Append(Address1Longitude).Append("\n");
            sb.Append("  Address1Addresstypecode: ").Append(Address1Addresstypecode).Append("\n");
            sb.Append("  Address2Postalcode: ").Append(Address2Postalcode).Append("\n");
            sb.Append("  Passportlo: ").Append(Passportlo).Append("\n");
            sb.Append("  Importsequencenumber: ").Append(Importsequencenumber).Append("\n");
            sb.Append("  Timezoneruleversionnumber: ").Append(Timezoneruleversionnumber).Append("\n");
            sb.Append("  Sharepointemailaddress: ").Append(Sharepointemailaddress).Append("\n");
            sb.Append("  Yammeruserid: ").Append(Yammeruserid).Append("\n");
            sb.Append("  Nickname: ").Append(Nickname).Append("\n");
            sb.Append("  Address1Composite: ").Append(Address1Composite).Append("\n");
            sb.Append("  Overriddencreatedon: ").Append(Overriddencreatedon).Append("\n");
            sb.Append("  Personalemailaddress: ").Append(Personalemailaddress).Append("\n");
            sb.Append("  Utcconversiontimezonecode: ").Append(Utcconversiontimezonecode).Append("\n");
            sb.Append("  Preferredemailcode: ").Append(Preferredemailcode).Append("\n");
            sb.Append("  Address2Composite: ").Append(Address2Composite).Append("\n");
            sb.Append("  Address1Telephone1: ").Append(Address1Telephone1).Append("\n");
            sb.Append("  MobileofflineprofileidValue: ").Append(MobileofflineprofileidValue).Append("\n");
            sb.Append("  Address2Country: ").Append(Address2Country).Append("\n");
            sb.Append("  Address1Line1: ").Append(Address1Line1).Append("\n");
            sb.Append("  Yomimiddlename: ").Append(Yomimiddlename).Append("\n");
            sb.Append("  TransactioncurrencyidValue: ").Append(TransactioncurrencyidValue).Append("\n");
            sb.Append("  Address1Line3: ").Append(Address1Line3).Append("\n");
            sb.Append("  Address1Line2: ").Append(Address1Line2).Append("\n");
            sb.Append("  Address1City: ").Append(Address1City).Append("\n");
            sb.Append("  Disabledreason: ").Append(Disabledreason).Append("\n");
            sb.Append("  Address2Name: ").Append(Address2Name).Append("\n");
            sb.Append("  PositionidValue: ").Append(PositionidValue).Append("\n");
            sb.Append("  Address2Line1: ").Append(Address2Line1).Append("\n");
            sb.Append("  Middlename: ").Append(Middlename).Append("\n");
            sb.Append("  Preferredphonecode: ").Append(Preferredphonecode).Append("\n");
            sb.Append("  Employeeid: ").Append(Employeeid).Append("\n");
            sb.Append("  Mobilealertemail: ").Append(Mobilealertemail).Append("\n");
            sb.Append("  Address2Telephone2: ").Append(Address2Telephone2).Append("\n");
            sb.Append("  Address2Telephone1: ").Append(Address2Telephone1).Append("\n");
            sb.Append("  Traversedpath: ").Append(Traversedpath).Append("\n");
            sb.Append("  Address2County: ").Append(Address2County).Append("\n");
            sb.Append("  Yomifirstname: ").Append(Yomifirstname).Append("\n");
            sb.Append("  Address2Shippingmethodcode: ").Append(Address2Shippingmethodcode).Append("\n");
            sb.Append("  Address2Telephone3: ").Append(Address2Telephone3).Append("\n");
            sb.Append("  Yomilastname: ").Append(Yomilastname).Append("\n");
            sb.Append("  Displayinserviceviews: ").Append(Displayinserviceviews).Append("\n");
            sb.Append("  Address2Addresstypecode: ").Append(Address2Addresstypecode).Append("\n");
            sb.Append("  Yammeremailaddress: ").Append(Yammeremailaddress).Append("\n");
            sb.Append("  Address1Postalcode: ").Append(Address1Postalcode).Append("\n");
            sb.Append("  Exchangerate: ").Append(Exchangerate).Append("\n");
            sb.Append("  Jobtitle: ").Append(Jobtitle).Append("\n");
            sb.Append("  Address2Postofficebox: ").Append(Address2Postofficebox).Append("\n");
            sb.Append("  Address2Upszone: ").Append(Address2Upszone).Append("\n");
            sb.Append("  Processid: ").Append(Processid).Append("\n");
            sb.Append("  Applicationiduri: ").Append(Applicationiduri).Append("\n");
            sb.Append("  Address2Utcoffset: ").Append(Address2Utcoffset).Append("\n");
            sb.Append("  Address1Telephone2: ").Append(Address1Telephone2).Append("\n");
            sb.Append("  Address1Country: ").Append(Address1Country).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponseDefault3)obj);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault3 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponseDefault3 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault3 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OdataContext == other.OdataContext ||
                    OdataContext != null &&
                    OdataContext.Equals(other.OdataContext)
                ) && 
                (
                    OdataEtag == other.OdataEtag ||
                    OdataEtag != null &&
                    OdataEtag.Equals(other.OdataEtag)
                ) && 
                (
                    Systemuserid == other.Systemuserid ||
                    Systemuserid != null &&
                    Systemuserid.Equals(other.Systemuserid)
                ) && 
                (
                    Accessmode == other.Accessmode ||
                    Accessmode != null &&
                    Accessmode.Equals(other.Accessmode)
                ) && 
                (
                    Firstname == other.Firstname ||
                    Firstname != null &&
                    Firstname.Equals(other.Firstname)
                ) && 
                (
                    Setupuser == other.Setupuser ||
                    Setupuser != null &&
                    Setupuser.Equals(other.Setupuser)
                ) && 
                (
                    Address1Addressid == other.Address1Addressid ||
                    Address1Addressid != null &&
                    Address1Addressid.Equals(other.Address1Addressid)
                ) && 
                (
                    Incomingemaildeliverymethod == other.Incomingemaildeliverymethod ||
                    Incomingemaildeliverymethod != null &&
                    Incomingemaildeliverymethod.Equals(other.Incomingemaildeliverymethod)
                ) && 
                (
                    Internalemailaddress == other.Internalemailaddress ||
                    Internalemailaddress != null &&
                    Internalemailaddress.Equals(other.Internalemailaddress)
                ) && 
                (
                    Identityid == other.Identityid ||
                    Identityid != null &&
                    Identityid.Equals(other.Identityid)
                ) && 
                (
                    Domainname == other.Domainname ||
                    Domainname != null &&
                    Domainname.Equals(other.Domainname)
                ) && 
                (
                    QueueidValue == other.QueueidValue ||
                    QueueidValue != null &&
                    QueueidValue.Equals(other.QueueidValue)
                ) && 
                (
                    Entityimageid == other.Entityimageid ||
                    Entityimageid != null &&
                    Entityimageid.Equals(other.Entityimageid)
                ) && 
                (
                    Isintegrationuser == other.Isintegrationuser ||
                    Isintegrationuser != null &&
                    Isintegrationuser.Equals(other.Isintegrationuser)
                ) && 
                (
                    Createdon == other.Createdon ||
                    Createdon != null &&
                    Createdon.Equals(other.Createdon)
                ) && 
                (
                    EntityimageTimestamp == other.EntityimageTimestamp ||
                    EntityimageTimestamp != null &&
                    EntityimageTimestamp.Equals(other.EntityimageTimestamp)
                ) && 
                (
                    CalendaridValue == other.CalendaridValue ||
                    CalendaridValue != null &&
                    CalendaridValue.Equals(other.CalendaridValue)
                ) && 
                (
                    Windowsliveid == other.Windowsliveid ||
                    Windowsliveid != null &&
                    Windowsliveid.Equals(other.Windowsliveid)
                ) && 
                (
                    BusinessunitidValue == other.BusinessunitidValue ||
                    BusinessunitidValue != null &&
                    BusinessunitidValue.Equals(other.BusinessunitidValue)
                ) && 
                (
                    Caltype == other.Caltype ||
                    Caltype != null &&
                    Caltype.Equals(other.Caltype)
                ) && 
                (
                    Modifiedon == other.Modifiedon ||
                    Modifiedon != null &&
                    Modifiedon.Equals(other.Modifiedon)
                ) && 
                (
                    Defaultfilterspopulated == other.Defaultfilterspopulated ||
                    Defaultfilterspopulated != null &&
                    Defaultfilterspopulated.Equals(other.Defaultfilterspopulated)
                ) && 
                (
                    Outgoingemaildeliverymethod == other.Outgoingemaildeliverymethod ||
                    Outgoingemaildeliverymethod != null &&
                    Outgoingemaildeliverymethod.Equals(other.Outgoingemaildeliverymethod)
                ) && 
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    Emailrouteraccessapproval == other.Emailrouteraccessapproval ||
                    Emailrouteraccessapproval != null &&
                    Emailrouteraccessapproval.Equals(other.Emailrouteraccessapproval)
                ) && 
                (
                    Lastname == other.Lastname ||
                    Lastname != null &&
                    Lastname.Equals(other.Lastname)
                ) && 
                (
                    Fullname == other.Fullname ||
                    Fullname != null &&
                    Fullname.Equals(other.Fullname)
                ) && 
                (
                    Issyncwithdirectory == other.Issyncwithdirectory ||
                    Issyncwithdirectory != null &&
                    Issyncwithdirectory.Equals(other.Issyncwithdirectory)
                ) && 
                (
                    Userlicensetype == other.Userlicensetype ||
                    Userlicensetype != null &&
                    Userlicensetype.Equals(other.Userlicensetype)
                ) && 
                (
                    Azureactivedirectoryobjectid == other.Azureactivedirectoryobjectid ||
                    Azureactivedirectoryobjectid != null &&
                    Azureactivedirectoryobjectid.Equals(other.Azureactivedirectoryobjectid)
                ) && 
                (
                    ModifiedbyValue == other.ModifiedbyValue ||
                    ModifiedbyValue != null &&
                    ModifiedbyValue.Equals(other.ModifiedbyValue)
                ) && 
                (
                    Organizationid == other.Organizationid ||
                    Organizationid != null &&
                    Organizationid.Equals(other.Organizationid)
                ) && 
                (
                    Defaultodbfoldername == other.Defaultodbfoldername ||
                    Defaultodbfoldername != null &&
                    Defaultodbfoldername.Equals(other.Defaultodbfoldername)
                ) && 
                (
                    Versionnumber == other.Versionnumber ||
                    Versionnumber != null &&
                    Versionnumber.Equals(other.Versionnumber)
                ) && 
                (
                    Isemailaddressapprovedbyo365admin == other.Isemailaddressapprovedbyo365admin ||
                    Isemailaddressapprovedbyo365admin != null &&
                    Isemailaddressapprovedbyo365admin.Equals(other.Isemailaddressapprovedbyo365admin)
                ) && 
                (
                    Invitestatuscode == other.Invitestatuscode ||
                    Invitestatuscode != null &&
                    Invitestatuscode.Equals(other.Invitestatuscode)
                ) && 
                (
                    Yomifullname == other.Yomifullname ||
                    Yomifullname != null &&
                    Yomifullname.Equals(other.Yomifullname)
                ) && 
                (
                    EntityimageUrl == other.EntityimageUrl ||
                    EntityimageUrl != null &&
                    EntityimageUrl.Equals(other.EntityimageUrl)
                ) && 
                (
                    Isdisabled == other.Isdisabled ||
                    Isdisabled != null &&
                    Isdisabled.Equals(other.Isdisabled)
                ) && 
                (
                    Userpuid == other.Userpuid ||
                    Userpuid != null &&
                    Userpuid.Equals(other.Userpuid)
                ) && 
                (
                    Address2Addressid == other.Address2Addressid ||
                    Address2Addressid != null &&
                    Address2Addressid.Equals(other.Address2Addressid)
                ) && 
                (
                    DefaultmailboxValue == other.DefaultmailboxValue ||
                    DefaultmailboxValue != null &&
                    DefaultmailboxValue.Equals(other.DefaultmailboxValue)
                ) && 
                (
                    Entityimage == other.Entityimage ||
                    Entityimage != null &&
                    Entityimage.Equals(other.Entityimage)
                ) && 
                (
                    Islicensed == other.Islicensed ||
                    Islicensed != null &&
                    Islicensed.Equals(other.Islicensed)
                ) && 
                (
                    Ownerid == other.Ownerid ||
                    Ownerid != null &&
                    Ownerid.Equals(other.Ownerid)
                ) && 
                (
                    Address1Fax == other.Address1Fax ||
                    Address1Fax != null &&
                    Address1Fax.Equals(other.Address1Fax)
                ) && 
                (
                    Address1Postofficebox == other.Address1Postofficebox ||
                    Address1Postofficebox != null &&
                    Address1Postofficebox.Equals(other.Address1Postofficebox)
                ) && 
                (
                    Address1Upszone == other.Address1Upszone ||
                    Address1Upszone != null &&
                    Address1Upszone.Equals(other.Address1Upszone)
                ) && 
                (
                    Photourl == other.Photourl ||
                    Photourl != null &&
                    Photourl.Equals(other.Photourl)
                ) && 
                (
                    Address1Latitude == other.Address1Latitude ||
                    Address1Latitude != null &&
                    Address1Latitude.Equals(other.Address1Latitude)
                ) && 
                (
                    Address1Shippingmethodcode == other.Address1Shippingmethodcode ||
                    Address1Shippingmethodcode != null &&
                    Address1Shippingmethodcode.Equals(other.Address1Shippingmethodcode)
                ) && 
                (
                    Address1Utcoffset == other.Address1Utcoffset ||
                    Address1Utcoffset != null &&
                    Address1Utcoffset.Equals(other.Address1Utcoffset)
                ) && 
                (
                    CreatedonbehalfbyValue == other.CreatedonbehalfbyValue ||
                    CreatedonbehalfbyValue != null &&
                    CreatedonbehalfbyValue.Equals(other.CreatedonbehalfbyValue)
                ) && 
                (
                    Homephone == other.Homephone ||
                    Homephone != null &&
                    Homephone.Equals(other.Homephone)
                ) && 
                (
                    Skills == other.Skills ||
                    Skills != null &&
                    Skills.Equals(other.Skills)
                ) && 
                (
                    Address2Latitude == other.Address2Latitude ||
                    Address2Latitude != null &&
                    Address2Latitude.Equals(other.Address2Latitude)
                ) && 
                (
                    CatFullnameValue == other.CatFullnameValue ||
                    CatFullnameValue != null &&
                    CatFullnameValue.Equals(other.CatFullnameValue)
                ) && 
                (
                    CreatedbyValue == other.CreatedbyValue ||
                    CreatedbyValue != null &&
                    CreatedbyValue.Equals(other.CreatedbyValue)
                ) && 
                (
                    Governmentid == other.Governmentid ||
                    Governmentid != null &&
                    Governmentid.Equals(other.Governmentid)
                ) && 
                (
                    ParentsystemuseridValue == other.ParentsystemuseridValue ||
                    ParentsystemuseridValue != null &&
                    ParentsystemuseridValue.Equals(other.ParentsystemuseridValue)
                ) && 
                (
                    Address2Stateorprovince == other.Address2Stateorprovince ||
                    Address2Stateorprovince != null &&
                    Address2Stateorprovince.Equals(other.Address2Stateorprovince)
                ) && 
                (
                    Address2Longitude == other.Address2Longitude ||
                    Address2Longitude != null &&
                    Address2Longitude.Equals(other.Address2Longitude)
                ) && 
                (
                    Address2City == other.Address2City ||
                    Address2City != null &&
                    Address2City.Equals(other.Address2City)
                ) && 
                (
                    Address1Telephone3 == other.Address1Telephone3 ||
                    Address1Telephone3 != null &&
                    Address1Telephone3.Equals(other.Address1Telephone3)
                ) && 
                (
                    Mobilephone == other.Mobilephone ||
                    Mobilephone != null &&
                    Mobilephone.Equals(other.Mobilephone)
                ) && 
                (
                    Address2Fax == other.Address2Fax ||
                    Address2Fax != null &&
                    Address2Fax.Equals(other.Address2Fax)
                ) && 
                (
                    Preferredaddresscode == other.Preferredaddresscode ||
                    Preferredaddresscode != null &&
                    Preferredaddresscode.Equals(other.Preferredaddresscode)
                ) && 
                (
                    Address1Name == other.Address1Name ||
                    Address1Name != null &&
                    Address1Name.Equals(other.Address1Name)
                ) && 
                (
                    Address2Line2 == other.Address2Line2 ||
                    Address2Line2 != null &&
                    Address2Line2.Equals(other.Address2Line2)
                ) && 
                (
                    Passporthi == other.Passporthi ||
                    Passporthi != null &&
                    Passporthi.Equals(other.Passporthi)
                ) && 
                (
                    TerritoryidValue == other.TerritoryidValue ||
                    TerritoryidValue != null &&
                    TerritoryidValue.Equals(other.TerritoryidValue)
                ) && 
                (
                    ModifiedonbehalfbyValue == other.ModifiedonbehalfbyValue ||
                    ModifiedonbehalfbyValue != null &&
                    ModifiedonbehalfbyValue.Equals(other.ModifiedonbehalfbyValue)
                ) && 
                (
                    Address1Stateorprovince == other.Address1Stateorprovince ||
                    Address1Stateorprovince != null &&
                    Address1Stateorprovince.Equals(other.Address1Stateorprovince)
                ) && 
                (
                    Applicationid == other.Applicationid ||
                    Applicationid != null &&
                    Applicationid.Equals(other.Applicationid)
                ) && 
                (
                    Salutation == other.Salutation ||
                    Salutation != null &&
                    Salutation.Equals(other.Salutation)
                ) && 
                (
                    Address1County == other.Address1County ||
                    Address1County != null &&
                    Address1County.Equals(other.Address1County)
                ) && 
                (
                    Address2Line3 == other.Address2Line3 ||
                    Address2Line3 != null &&
                    Address2Line3.Equals(other.Address2Line3)
                ) && 
                (
                    Stageid == other.Stageid ||
                    Stageid != null &&
                    Stageid.Equals(other.Stageid)
                ) && 
                (
                    Address1Longitude == other.Address1Longitude ||
                    Address1Longitude != null &&
                    Address1Longitude.Equals(other.Address1Longitude)
                ) && 
                (
                    Address1Addresstypecode == other.Address1Addresstypecode ||
                    Address1Addresstypecode != null &&
                    Address1Addresstypecode.Equals(other.Address1Addresstypecode)
                ) && 
                (
                    Address2Postalcode == other.Address2Postalcode ||
                    Address2Postalcode != null &&
                    Address2Postalcode.Equals(other.Address2Postalcode)
                ) && 
                (
                    Passportlo == other.Passportlo ||
                    Passportlo != null &&
                    Passportlo.Equals(other.Passportlo)
                ) && 
                (
                    Importsequencenumber == other.Importsequencenumber ||
                    Importsequencenumber != null &&
                    Importsequencenumber.Equals(other.Importsequencenumber)
                ) && 
                (
                    Timezoneruleversionnumber == other.Timezoneruleversionnumber ||
                    Timezoneruleversionnumber != null &&
                    Timezoneruleversionnumber.Equals(other.Timezoneruleversionnumber)
                ) && 
                (
                    Sharepointemailaddress == other.Sharepointemailaddress ||
                    Sharepointemailaddress != null &&
                    Sharepointemailaddress.Equals(other.Sharepointemailaddress)
                ) && 
                (
                    Yammeruserid == other.Yammeruserid ||
                    Yammeruserid != null &&
                    Yammeruserid.Equals(other.Yammeruserid)
                ) && 
                (
                    Nickname == other.Nickname ||
                    Nickname != null &&
                    Nickname.Equals(other.Nickname)
                ) && 
                (
                    Address1Composite == other.Address1Composite ||
                    Address1Composite != null &&
                    Address1Composite.Equals(other.Address1Composite)
                ) && 
                (
                    Overriddencreatedon == other.Overriddencreatedon ||
                    Overriddencreatedon != null &&
                    Overriddencreatedon.Equals(other.Overriddencreatedon)
                ) && 
                (
                    Personalemailaddress == other.Personalemailaddress ||
                    Personalemailaddress != null &&
                    Personalemailaddress.Equals(other.Personalemailaddress)
                ) && 
                (
                    Utcconversiontimezonecode == other.Utcconversiontimezonecode ||
                    Utcconversiontimezonecode != null &&
                    Utcconversiontimezonecode.Equals(other.Utcconversiontimezonecode)
                ) && 
                (
                    Preferredemailcode == other.Preferredemailcode ||
                    Preferredemailcode != null &&
                    Preferredemailcode.Equals(other.Preferredemailcode)
                ) && 
                (
                    Address2Composite == other.Address2Composite ||
                    Address2Composite != null &&
                    Address2Composite.Equals(other.Address2Composite)
                ) && 
                (
                    Address1Telephone1 == other.Address1Telephone1 ||
                    Address1Telephone1 != null &&
                    Address1Telephone1.Equals(other.Address1Telephone1)
                ) && 
                (
                    MobileofflineprofileidValue == other.MobileofflineprofileidValue ||
                    MobileofflineprofileidValue != null &&
                    MobileofflineprofileidValue.Equals(other.MobileofflineprofileidValue)
                ) && 
                (
                    Address2Country == other.Address2Country ||
                    Address2Country != null &&
                    Address2Country.Equals(other.Address2Country)
                ) && 
                (
                    Address1Line1 == other.Address1Line1 ||
                    Address1Line1 != null &&
                    Address1Line1.Equals(other.Address1Line1)
                ) && 
                (
                    Yomimiddlename == other.Yomimiddlename ||
                    Yomimiddlename != null &&
                    Yomimiddlename.Equals(other.Yomimiddlename)
                ) && 
                (
                    TransactioncurrencyidValue == other.TransactioncurrencyidValue ||
                    TransactioncurrencyidValue != null &&
                    TransactioncurrencyidValue.Equals(other.TransactioncurrencyidValue)
                ) && 
                (
                    Address1Line3 == other.Address1Line3 ||
                    Address1Line3 != null &&
                    Address1Line3.Equals(other.Address1Line3)
                ) && 
                (
                    Address1Line2 == other.Address1Line2 ||
                    Address1Line2 != null &&
                    Address1Line2.Equals(other.Address1Line2)
                ) && 
                (
                    Address1City == other.Address1City ||
                    Address1City != null &&
                    Address1City.Equals(other.Address1City)
                ) && 
                (
                    Disabledreason == other.Disabledreason ||
                    Disabledreason != null &&
                    Disabledreason.Equals(other.Disabledreason)
                ) && 
                (
                    Address2Name == other.Address2Name ||
                    Address2Name != null &&
                    Address2Name.Equals(other.Address2Name)
                ) && 
                (
                    PositionidValue == other.PositionidValue ||
                    PositionidValue != null &&
                    PositionidValue.Equals(other.PositionidValue)
                ) && 
                (
                    Address2Line1 == other.Address2Line1 ||
                    Address2Line1 != null &&
                    Address2Line1.Equals(other.Address2Line1)
                ) && 
                (
                    Middlename == other.Middlename ||
                    Middlename != null &&
                    Middlename.Equals(other.Middlename)
                ) && 
                (
                    Preferredphonecode == other.Preferredphonecode ||
                    Preferredphonecode != null &&
                    Preferredphonecode.Equals(other.Preferredphonecode)
                ) && 
                (
                    Employeeid == other.Employeeid ||
                    Employeeid != null &&
                    Employeeid.Equals(other.Employeeid)
                ) && 
                (
                    Mobilealertemail == other.Mobilealertemail ||
                    Mobilealertemail != null &&
                    Mobilealertemail.Equals(other.Mobilealertemail)
                ) && 
                (
                    Address2Telephone2 == other.Address2Telephone2 ||
                    Address2Telephone2 != null &&
                    Address2Telephone2.Equals(other.Address2Telephone2)
                ) && 
                (
                    Address2Telephone1 == other.Address2Telephone1 ||
                    Address2Telephone1 != null &&
                    Address2Telephone1.Equals(other.Address2Telephone1)
                ) && 
                (
                    Traversedpath == other.Traversedpath ||
                    Traversedpath != null &&
                    Traversedpath.Equals(other.Traversedpath)
                ) && 
                (
                    Address2County == other.Address2County ||
                    Address2County != null &&
                    Address2County.Equals(other.Address2County)
                ) && 
                (
                    Yomifirstname == other.Yomifirstname ||
                    Yomifirstname != null &&
                    Yomifirstname.Equals(other.Yomifirstname)
                ) && 
                (
                    Address2Shippingmethodcode == other.Address2Shippingmethodcode ||
                    Address2Shippingmethodcode != null &&
                    Address2Shippingmethodcode.Equals(other.Address2Shippingmethodcode)
                ) && 
                (
                    Address2Telephone3 == other.Address2Telephone3 ||
                    Address2Telephone3 != null &&
                    Address2Telephone3.Equals(other.Address2Telephone3)
                ) && 
                (
                    Yomilastname == other.Yomilastname ||
                    Yomilastname != null &&
                    Yomilastname.Equals(other.Yomilastname)
                ) && 
                (
                    Displayinserviceviews == other.Displayinserviceviews ||
                    Displayinserviceviews != null &&
                    Displayinserviceviews.Equals(other.Displayinserviceviews)
                ) && 
                (
                    Address2Addresstypecode == other.Address2Addresstypecode ||
                    Address2Addresstypecode != null &&
                    Address2Addresstypecode.Equals(other.Address2Addresstypecode)
                ) && 
                (
                    Yammeremailaddress == other.Yammeremailaddress ||
                    Yammeremailaddress != null &&
                    Yammeremailaddress.Equals(other.Yammeremailaddress)
                ) && 
                (
                    Address1Postalcode == other.Address1Postalcode ||
                    Address1Postalcode != null &&
                    Address1Postalcode.Equals(other.Address1Postalcode)
                ) && 
                (
                    Exchangerate == other.Exchangerate ||
                    Exchangerate != null &&
                    Exchangerate.Equals(other.Exchangerate)
                ) && 
                (
                    Jobtitle == other.Jobtitle ||
                    Jobtitle != null &&
                    Jobtitle.Equals(other.Jobtitle)
                ) && 
                (
                    Address2Postofficebox == other.Address2Postofficebox ||
                    Address2Postofficebox != null &&
                    Address2Postofficebox.Equals(other.Address2Postofficebox)
                ) && 
                (
                    Address2Upszone == other.Address2Upszone ||
                    Address2Upszone != null &&
                    Address2Upszone.Equals(other.Address2Upszone)
                ) && 
                (
                    Processid == other.Processid ||
                    Processid != null &&
                    Processid.Equals(other.Processid)
                ) && 
                (
                    Applicationiduri == other.Applicationiduri ||
                    Applicationiduri != null &&
                    Applicationiduri.Equals(other.Applicationiduri)
                ) && 
                (
                    Address2Utcoffset == other.Address2Utcoffset ||
                    Address2Utcoffset != null &&
                    Address2Utcoffset.Equals(other.Address2Utcoffset)
                ) && 
                (
                    Address1Telephone2 == other.Address1Telephone2 ||
                    Address1Telephone2 != null &&
                    Address1Telephone2.Equals(other.Address1Telephone2)
                ) && 
                (
                    Address1Country == other.Address1Country ||
                    Address1Country != null &&
                    Address1Country.Equals(other.Address1Country)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (OdataContext != null)
                    hashCode = hashCode * 59 + OdataContext.GetHashCode();
                    if (OdataEtag != null)
                    hashCode = hashCode * 59 + OdataEtag.GetHashCode();
                    if (Systemuserid != null)
                    hashCode = hashCode * 59 + Systemuserid.GetHashCode();
                    if (Accessmode != null)
                    hashCode = hashCode * 59 + Accessmode.GetHashCode();
                    if (Firstname != null)
                    hashCode = hashCode * 59 + Firstname.GetHashCode();
                    if (Setupuser != null)
                    hashCode = hashCode * 59 + Setupuser.GetHashCode();
                    if (Address1Addressid != null)
                    hashCode = hashCode * 59 + Address1Addressid.GetHashCode();
                    if (Incomingemaildeliverymethod != null)
                    hashCode = hashCode * 59 + Incomingemaildeliverymethod.GetHashCode();
                    if (Internalemailaddress != null)
                    hashCode = hashCode * 59 + Internalemailaddress.GetHashCode();
                    if (Identityid != null)
                    hashCode = hashCode * 59 + Identityid.GetHashCode();
                    if (Domainname != null)
                    hashCode = hashCode * 59 + Domainname.GetHashCode();
                    if (QueueidValue != null)
                    hashCode = hashCode * 59 + QueueidValue.GetHashCode();
                    if (Entityimageid != null)
                    hashCode = hashCode * 59 + Entityimageid.GetHashCode();
                    if (Isintegrationuser != null)
                    hashCode = hashCode * 59 + Isintegrationuser.GetHashCode();
                    if (Createdon != null)
                    hashCode = hashCode * 59 + Createdon.GetHashCode();
                    if (EntityimageTimestamp != null)
                    hashCode = hashCode * 59 + EntityimageTimestamp.GetHashCode();
                    if (CalendaridValue != null)
                    hashCode = hashCode * 59 + CalendaridValue.GetHashCode();
                    if (Windowsliveid != null)
                    hashCode = hashCode * 59 + Windowsliveid.GetHashCode();
                    if (BusinessunitidValue != null)
                    hashCode = hashCode * 59 + BusinessunitidValue.GetHashCode();
                    if (Caltype != null)
                    hashCode = hashCode * 59 + Caltype.GetHashCode();
                    if (Modifiedon != null)
                    hashCode = hashCode * 59 + Modifiedon.GetHashCode();
                    if (Defaultfilterspopulated != null)
                    hashCode = hashCode * 59 + Defaultfilterspopulated.GetHashCode();
                    if (Outgoingemaildeliverymethod != null)
                    hashCode = hashCode * 59 + Outgoingemaildeliverymethod.GetHashCode();
                    if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                    if (Emailrouteraccessapproval != null)
                    hashCode = hashCode * 59 + Emailrouteraccessapproval.GetHashCode();
                    if (Lastname != null)
                    hashCode = hashCode * 59 + Lastname.GetHashCode();
                    if (Fullname != null)
                    hashCode = hashCode * 59 + Fullname.GetHashCode();
                    if (Issyncwithdirectory != null)
                    hashCode = hashCode * 59 + Issyncwithdirectory.GetHashCode();
                    if (Userlicensetype != null)
                    hashCode = hashCode * 59 + Userlicensetype.GetHashCode();
                    if (Azureactivedirectoryobjectid != null)
                    hashCode = hashCode * 59 + Azureactivedirectoryobjectid.GetHashCode();
                    if (ModifiedbyValue != null)
                    hashCode = hashCode * 59 + ModifiedbyValue.GetHashCode();
                    if (Organizationid != null)
                    hashCode = hashCode * 59 + Organizationid.GetHashCode();
                    if (Defaultodbfoldername != null)
                    hashCode = hashCode * 59 + Defaultodbfoldername.GetHashCode();
                    if (Versionnumber != null)
                    hashCode = hashCode * 59 + Versionnumber.GetHashCode();
                    if (Isemailaddressapprovedbyo365admin != null)
                    hashCode = hashCode * 59 + Isemailaddressapprovedbyo365admin.GetHashCode();
                    if (Invitestatuscode != null)
                    hashCode = hashCode * 59 + Invitestatuscode.GetHashCode();
                    if (Yomifullname != null)
                    hashCode = hashCode * 59 + Yomifullname.GetHashCode();
                    if (EntityimageUrl != null)
                    hashCode = hashCode * 59 + EntityimageUrl.GetHashCode();
                    if (Isdisabled != null)
                    hashCode = hashCode * 59 + Isdisabled.GetHashCode();
                    if (Userpuid != null)
                    hashCode = hashCode * 59 + Userpuid.GetHashCode();
                    if (Address2Addressid != null)
                    hashCode = hashCode * 59 + Address2Addressid.GetHashCode();
                    if (DefaultmailboxValue != null)
                    hashCode = hashCode * 59 + DefaultmailboxValue.GetHashCode();
                    if (Entityimage != null)
                    hashCode = hashCode * 59 + Entityimage.GetHashCode();
                    if (Islicensed != null)
                    hashCode = hashCode * 59 + Islicensed.GetHashCode();
                    if (Ownerid != null)
                    hashCode = hashCode * 59 + Ownerid.GetHashCode();
                    if (Address1Fax != null)
                    hashCode = hashCode * 59 + Address1Fax.GetHashCode();
                    if (Address1Postofficebox != null)
                    hashCode = hashCode * 59 + Address1Postofficebox.GetHashCode();
                    if (Address1Upszone != null)
                    hashCode = hashCode * 59 + Address1Upszone.GetHashCode();
                    if (Photourl != null)
                    hashCode = hashCode * 59 + Photourl.GetHashCode();
                    if (Address1Latitude != null)
                    hashCode = hashCode * 59 + Address1Latitude.GetHashCode();
                    if (Address1Shippingmethodcode != null)
                    hashCode = hashCode * 59 + Address1Shippingmethodcode.GetHashCode();
                    if (Address1Utcoffset != null)
                    hashCode = hashCode * 59 + Address1Utcoffset.GetHashCode();
                    if (CreatedonbehalfbyValue != null)
                    hashCode = hashCode * 59 + CreatedonbehalfbyValue.GetHashCode();
                    if (Homephone != null)
                    hashCode = hashCode * 59 + Homephone.GetHashCode();
                    if (Skills != null)
                    hashCode = hashCode * 59 + Skills.GetHashCode();
                    if (Address2Latitude != null)
                    hashCode = hashCode * 59 + Address2Latitude.GetHashCode();
                    if (CatFullnameValue != null)
                    hashCode = hashCode * 59 + CatFullnameValue.GetHashCode();
                    if (CreatedbyValue != null)
                    hashCode = hashCode * 59 + CreatedbyValue.GetHashCode();
                    if (Governmentid != null)
                    hashCode = hashCode * 59 + Governmentid.GetHashCode();
                    if (ParentsystemuseridValue != null)
                    hashCode = hashCode * 59 + ParentsystemuseridValue.GetHashCode();
                    if (Address2Stateorprovince != null)
                    hashCode = hashCode * 59 + Address2Stateorprovince.GetHashCode();
                    if (Address2Longitude != null)
                    hashCode = hashCode * 59 + Address2Longitude.GetHashCode();
                    if (Address2City != null)
                    hashCode = hashCode * 59 + Address2City.GetHashCode();
                    if (Address1Telephone3 != null)
                    hashCode = hashCode * 59 + Address1Telephone3.GetHashCode();
                    if (Mobilephone != null)
                    hashCode = hashCode * 59 + Mobilephone.GetHashCode();
                    if (Address2Fax != null)
                    hashCode = hashCode * 59 + Address2Fax.GetHashCode();
                    if (Preferredaddresscode != null)
                    hashCode = hashCode * 59 + Preferredaddresscode.GetHashCode();
                    if (Address1Name != null)
                    hashCode = hashCode * 59 + Address1Name.GetHashCode();
                    if (Address2Line2 != null)
                    hashCode = hashCode * 59 + Address2Line2.GetHashCode();
                    if (Passporthi != null)
                    hashCode = hashCode * 59 + Passporthi.GetHashCode();
                    if (TerritoryidValue != null)
                    hashCode = hashCode * 59 + TerritoryidValue.GetHashCode();
                    if (ModifiedonbehalfbyValue != null)
                    hashCode = hashCode * 59 + ModifiedonbehalfbyValue.GetHashCode();
                    if (Address1Stateorprovince != null)
                    hashCode = hashCode * 59 + Address1Stateorprovince.GetHashCode();
                    if (Applicationid != null)
                    hashCode = hashCode * 59 + Applicationid.GetHashCode();
                    if (Salutation != null)
                    hashCode = hashCode * 59 + Salutation.GetHashCode();
                    if (Address1County != null)
                    hashCode = hashCode * 59 + Address1County.GetHashCode();
                    if (Address2Line3 != null)
                    hashCode = hashCode * 59 + Address2Line3.GetHashCode();
                    if (Stageid != null)
                    hashCode = hashCode * 59 + Stageid.GetHashCode();
                    if (Address1Longitude != null)
                    hashCode = hashCode * 59 + Address1Longitude.GetHashCode();
                    if (Address1Addresstypecode != null)
                    hashCode = hashCode * 59 + Address1Addresstypecode.GetHashCode();
                    if (Address2Postalcode != null)
                    hashCode = hashCode * 59 + Address2Postalcode.GetHashCode();
                    if (Passportlo != null)
                    hashCode = hashCode * 59 + Passportlo.GetHashCode();
                    if (Importsequencenumber != null)
                    hashCode = hashCode * 59 + Importsequencenumber.GetHashCode();
                    if (Timezoneruleversionnumber != null)
                    hashCode = hashCode * 59 + Timezoneruleversionnumber.GetHashCode();
                    if (Sharepointemailaddress != null)
                    hashCode = hashCode * 59 + Sharepointemailaddress.GetHashCode();
                    if (Yammeruserid != null)
                    hashCode = hashCode * 59 + Yammeruserid.GetHashCode();
                    if (Nickname != null)
                    hashCode = hashCode * 59 + Nickname.GetHashCode();
                    if (Address1Composite != null)
                    hashCode = hashCode * 59 + Address1Composite.GetHashCode();
                    if (Overriddencreatedon != null)
                    hashCode = hashCode * 59 + Overriddencreatedon.GetHashCode();
                    if (Personalemailaddress != null)
                    hashCode = hashCode * 59 + Personalemailaddress.GetHashCode();
                    if (Utcconversiontimezonecode != null)
                    hashCode = hashCode * 59 + Utcconversiontimezonecode.GetHashCode();
                    if (Preferredemailcode != null)
                    hashCode = hashCode * 59 + Preferredemailcode.GetHashCode();
                    if (Address2Composite != null)
                    hashCode = hashCode * 59 + Address2Composite.GetHashCode();
                    if (Address1Telephone1 != null)
                    hashCode = hashCode * 59 + Address1Telephone1.GetHashCode();
                    if (MobileofflineprofileidValue != null)
                    hashCode = hashCode * 59 + MobileofflineprofileidValue.GetHashCode();
                    if (Address2Country != null)
                    hashCode = hashCode * 59 + Address2Country.GetHashCode();
                    if (Address1Line1 != null)
                    hashCode = hashCode * 59 + Address1Line1.GetHashCode();
                    if (Yomimiddlename != null)
                    hashCode = hashCode * 59 + Yomimiddlename.GetHashCode();
                    if (TransactioncurrencyidValue != null)
                    hashCode = hashCode * 59 + TransactioncurrencyidValue.GetHashCode();
                    if (Address1Line3 != null)
                    hashCode = hashCode * 59 + Address1Line3.GetHashCode();
                    if (Address1Line2 != null)
                    hashCode = hashCode * 59 + Address1Line2.GetHashCode();
                    if (Address1City != null)
                    hashCode = hashCode * 59 + Address1City.GetHashCode();
                    if (Disabledreason != null)
                    hashCode = hashCode * 59 + Disabledreason.GetHashCode();
                    if (Address2Name != null)
                    hashCode = hashCode * 59 + Address2Name.GetHashCode();
                    if (PositionidValue != null)
                    hashCode = hashCode * 59 + PositionidValue.GetHashCode();
                    if (Address2Line1 != null)
                    hashCode = hashCode * 59 + Address2Line1.GetHashCode();
                    if (Middlename != null)
                    hashCode = hashCode * 59 + Middlename.GetHashCode();
                    if (Preferredphonecode != null)
                    hashCode = hashCode * 59 + Preferredphonecode.GetHashCode();
                    if (Employeeid != null)
                    hashCode = hashCode * 59 + Employeeid.GetHashCode();
                    if (Mobilealertemail != null)
                    hashCode = hashCode * 59 + Mobilealertemail.GetHashCode();
                    if (Address2Telephone2 != null)
                    hashCode = hashCode * 59 + Address2Telephone2.GetHashCode();
                    if (Address2Telephone1 != null)
                    hashCode = hashCode * 59 + Address2Telephone1.GetHashCode();
                    if (Traversedpath != null)
                    hashCode = hashCode * 59 + Traversedpath.GetHashCode();
                    if (Address2County != null)
                    hashCode = hashCode * 59 + Address2County.GetHashCode();
                    if (Yomifirstname != null)
                    hashCode = hashCode * 59 + Yomifirstname.GetHashCode();
                    if (Address2Shippingmethodcode != null)
                    hashCode = hashCode * 59 + Address2Shippingmethodcode.GetHashCode();
                    if (Address2Telephone3 != null)
                    hashCode = hashCode * 59 + Address2Telephone3.GetHashCode();
                    if (Yomilastname != null)
                    hashCode = hashCode * 59 + Yomilastname.GetHashCode();
                    if (Displayinserviceviews != null)
                    hashCode = hashCode * 59 + Displayinserviceviews.GetHashCode();
                    if (Address2Addresstypecode != null)
                    hashCode = hashCode * 59 + Address2Addresstypecode.GetHashCode();
                    if (Yammeremailaddress != null)
                    hashCode = hashCode * 59 + Yammeremailaddress.GetHashCode();
                    if (Address1Postalcode != null)
                    hashCode = hashCode * 59 + Address1Postalcode.GetHashCode();
                    if (Exchangerate != null)
                    hashCode = hashCode * 59 + Exchangerate.GetHashCode();
                    if (Jobtitle != null)
                    hashCode = hashCode * 59 + Jobtitle.GetHashCode();
                    if (Address2Postofficebox != null)
                    hashCode = hashCode * 59 + Address2Postofficebox.GetHashCode();
                    if (Address2Upszone != null)
                    hashCode = hashCode * 59 + Address2Upszone.GetHashCode();
                    if (Processid != null)
                    hashCode = hashCode * 59 + Processid.GetHashCode();
                    if (Applicationiduri != null)
                    hashCode = hashCode * 59 + Applicationiduri.GetHashCode();
                    if (Address2Utcoffset != null)
                    hashCode = hashCode * 59 + Address2Utcoffset.GetHashCode();
                    if (Address1Telephone2 != null)
                    hashCode = hashCode * 59 + Address1Telephone2.GetHashCode();
                    if (Address1Country != null)
                    hashCode = hashCode * 59 + Address1Country.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponseDefault3 left, InlineResponseDefault3 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponseDefault3 left, InlineResponseDefault3 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
