/*
 * CDS - GtmEntries
 *
 * CDS - GtmEntries
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIMDemo.Models
{ 
    /// <summary>
    /// Field
    /// </summary>
    [DataContract]
    public partial class InlineResponseDefault2Field : IEquatable<InlineResponseDefault2Field>
    { 
        /// <summary>
        /// AttributeName
        /// </summary>
        /// <value>AttributeName</value>
        [DataMember(Name="AttributeName")]
        public string AttributeName { get; set; }

        /// <summary>
        /// IsRequired
        /// </summary>
        /// <value>IsRequired</value>
        [DataMember(Name="IsRequired")]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault2Field {\n");
            sb.Append("  AttributeName: ").Append(AttributeName).Append("\n");
            sb.Append("  IsRequired: ").Append(IsRequired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponseDefault2Field)obj);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault2Field instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponseDefault2Field to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault2Field other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AttributeName == other.AttributeName ||
                    AttributeName != null &&
                    AttributeName.Equals(other.AttributeName)
                ) && 
                (
                    IsRequired == other.IsRequired ||
                    IsRequired != null &&
                    IsRequired.Equals(other.IsRequired)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AttributeName != null)
                    hashCode = hashCode * 59 + AttributeName.GetHashCode();
                    if (IsRequired != null)
                    hashCode = hashCode * 59 + IsRequired.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponseDefault2Field left, InlineResponseDefault2Field right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponseDefault2Field left, InlineResponseDefault2Field right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
