/*
 * CDS - GtmEntries
 *
 * CDS - GtmEntries
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIMDemo.Models
{ 
    /// <summary>
    /// IsCustomizable
    /// </summary>
    [DataContract]
    public partial class InlineResponseDefault6OptionSetIsCustomizable : IEquatable<InlineResponseDefault6OptionSetIsCustomizable>
    { 
        /// <summary>
        /// Value
        /// </summary>
        /// <value>Value</value>
        [DataMember(Name="Value")]
        public bool? Value { get; set; }

        /// <summary>
        /// CanBeChanged
        /// </summary>
        /// <value>CanBeChanged</value>
        [DataMember(Name="CanBeChanged")]
        public bool? CanBeChanged { get; set; }

        /// <summary>
        /// ManagedPropertyLogicalName
        /// </summary>
        /// <value>ManagedPropertyLogicalName</value>
        [DataMember(Name="ManagedPropertyLogicalName")]
        public string ManagedPropertyLogicalName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault6OptionSetIsCustomizable {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  CanBeChanged: ").Append(CanBeChanged).Append("\n");
            sb.Append("  ManagedPropertyLogicalName: ").Append(ManagedPropertyLogicalName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponseDefault6OptionSetIsCustomizable)obj);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault6OptionSetIsCustomizable instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponseDefault6OptionSetIsCustomizable to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault6OptionSetIsCustomizable other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Value == other.Value ||
                    Value != null &&
                    Value.Equals(other.Value)
                ) && 
                (
                    CanBeChanged == other.CanBeChanged ||
                    CanBeChanged != null &&
                    CanBeChanged.Equals(other.CanBeChanged)
                ) && 
                (
                    ManagedPropertyLogicalName == other.ManagedPropertyLogicalName ||
                    ManagedPropertyLogicalName != null &&
                    ManagedPropertyLogicalName.Equals(other.ManagedPropertyLogicalName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (CanBeChanged != null)
                    hashCode = hashCode * 59 + CanBeChanged.GetHashCode();
                    if (ManagedPropertyLogicalName != null)
                    hashCode = hashCode * 59 + ManagedPropertyLogicalName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponseDefault6OptionSetIsCustomizable left, InlineResponseDefault6OptionSetIsCustomizable right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponseDefault6OptionSetIsCustomizable left, InlineResponseDefault6OptionSetIsCustomizable right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
